# -*- coding: utf-8 -*-
{
    "name": "Trinity Roots :: Account Deposit",
    "summary": "Account Deposit",
    "version": "10.0.1.0.0",
    "category": "Uncategorized",
    "website": "http://www.trinityroots.co.th/",
    "author": "Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {
        "python": [],
        "bin": [],
    },
    # any module necessary for this one to work correctly
    'depends': [
        'ofm_access_right_center',
        'base',
        'account',
        'sale',
        'sale_stock',
        'product',
        'account_cancel',
        'purchase_request',
        'ofm_purchase_request',
        'ofm_so_ext',
        'ofm_custom_tr_account_v10',
        'account_payment_method',
        'ofm_product_ext',
        'widget_allow_number',
        'tr_core_update',
    ],
    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'data/system_parameter.xml',
        'data/product_product.xml',
        'data/payment_method_data.xml',
        'data/so_payment_type_data.xml',
        'wizards/account_invoice_refund_view.xml',
        'wizards/so_payments_wizard_view.xml',
        'wizards/confirm_without_deposit_wizard.xml',
        'wizards/deposit_stock_picking_return_views.xml',
        'wizards/monthly_sales_so_tax_report_view.xml',
        'wizards/sales_so_tax_report_view.xml',
        'wizards/sales_so_return_tax_report_view.xml',
        'wizards/monthly_sales_so_return_tax_report_view.xml',
        'views/account_deposit_view.xml',
        'views/account_move_view.xml',
        'views/res_bank_view.xml',
        'views/account_tax_view.xml',
        'views/account_invoice_view.xml',
        'views/sale_view.xml',
        'views/payment_method.xml',
        'views/system_parameter.xml',
    ],
    'demo': [],

}
