from . import account
from . import account_chart_template
from . import account_invoice
from . import account_journal
from . import account_chart_template
from . import point_of_sale
from . import account_billing_note
from . import res_company
from . import account_move
from . import account_payment
from . import payment_method
from . import res_partner
from . import sale_order
from . import account_payment_by_invoice
from . import res_config
from . import chart_template
